sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - sourc $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  #  Run the below 3 commands in google cloud console terminal as well
  - gcloud config set project k8s-demo-313408
  - gcloud config set compute/zone LOCATION_FROM_KUBERNETES_ENGINE
  - gcloud container clusters get-credentials CLUSTER_NAME
  # end
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
  - dokcer build -t abhipatel7/kubernetes-demo -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhipatel7/kubernetes-demo npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main